spring:
  main:
    web-application-type: reactive
  application:
    name: cart-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8082   # HTTP (Tomcat) port
