eureka:
  instance:
    hostname: eureka8889.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka8888.com:8888/eureka/
server:
  port: 8889

